import { NextPage } from "next";
import Link from "next/link";
import { gql } from "graphql-request";
import { GraphCmsApi } from "../../Services/GraphcmsApi";
import Head from "next/head";
import React from "react";
import Nav from "../../common/Nav";
import Hero from "../../modules/Collection/Hero";
import Items from "../../modules/Collection/Items";
import { ItemsType } from "../../modules/Collection/Logic/Types";
import { CollectionBannersType } from "../../TypeScript/ReusableTypes";

import styles from "../../../styles/Collection/Hero.module.css";

//Graphcms
const QUERY = gql`
  query CollectionBanners($slug: String!) {
    collectionBanners(where: { slug: $slug }) {
      id
      collectionName
      collectionCoverPhoto {
        url
      }
    }
  }
`;
const QUERYITEM = gql`
  query Items($id: ID!) {
    items(where: { collectionBanners_some: { id: $id } }) {
      id
      productName
      productPrice
      productQuantity
      rating
      slug
      productPhoto {
        url
      }
    }
  }
`;
const SLUGLIST = gql`
  query {
    collectionBanners {
      id
      collectionName
      slug
      collectionCoverPhoto {
        url
      }
    }
  }
`;

export const getStaticPaths = async () => {
  const { collectionBanners } = await GraphCmsApi.request(SLUGLIST);
  return {
    paths: collectionBanners.map((collectionBanner: any) => ({
      params: { collection: collectionBanner.slug },
    })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }: any) => {
  const slug = params.collection;
  const { collectionBanners } = await GraphCmsApi.request(QUERY, { slug });
  const id = collectionBanners[0].id;
  const { items } = await GraphCmsApi.request(QUERYITEM, { id });
  return {
    props: { collectionBanners, items },
  };
};

interface Props {
  collectionBanners: CollectionBannersType[];
  items: ItemsType[];
}

const CollectionPage: NextPage<Props> = ({ collectionBanners, items }) => {
  return (
    <div>
      <Head>
        <title>Workoutly Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        <div className={styles.backArrow}>
          <Link href="/">
            <i className="fa-solid fa-circle-chevron-left"></i>
          </Link>
        </div>
        <Nav />
        <Hero CollectionBanner={collectionBanners} />
        <Items Items={items} />
      </main>
    </div>
  );
};

export default CollectionPage;
