import { NextPage } from "next";
import Head from "next/head";
import { gql } from "graphql-request";
import { GraphCmsApi } from "../../Services/GraphcmsApi";

import styles from "../../../styles/Item/Item.module.css";

//Graphcms
const QUERY = gql`
  query Item($slug: String!) {
    item(where: { slug: $slug }) {
      productName
      productPrice
      productQuantity
      rating
      description {
        text
      }
      productPhoto {
        url
      }
    }
  }
`;
const SLUGLIST = gql`
  {
    items {
      slug
    }
  }
`;

export const getStaticPaths = async () => {
  const { items } = await GraphCmsApi.request(SLUGLIST);
  return {
    paths: items.map((item: any) => ({ params: { item: item.slug } })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }: any) => {
  const slug = params.item;
  const { item } = await GraphCmsApi.request(QUERY, { slug });
  return {
    props: { item },
  };
};

const ItemPage: NextPage = ({ item }: any) => {
  return (
    <div>
      <Head>
        <title>Workoutly Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <main>
        <section className={styles.container}>
          <div className={styles.itemContainer}>
            <div className={styles.productPhotoContainer}>
              <img src={item.productPhoto.url} alt="" />
            </div>
            <div className={styles.productInfoContainer}>
              <h3 className={styles.itemName}>{item.productName}</h3>
              <p>Rating: {item.rating}</p>
              <div className={styles.descriptionContainer}>
                <h4>Details:</h4>
                <p>{item.description.text}</p>
              </div>
              <p className={styles.itemPrice}>{item.productPrice}</p>
              <p>Stock: {item.productQuantity}</p>
              <button>Add to Cart</button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default ItemPage;
