import type { NextPage } from "next";
import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import Nav from "../common/Nav";
import Hero from "../modules/Home/Hero";
import Categories from "../modules/Home/Categories";
import FeaturedItems from "../modules/Home/FeaturedItems";
import Blog from "../modules/Home/Blog";
import LimitedItem from "../modules/Home/LimitedItem";
import Footer from "../modules/Home/Footer/Footer";
import { CollectionBannersType } from "../TypeScript/ReusableTypes";
import {
  CategoriesType,
  ItemsType,
  LimitedItemType,
} from "../modules/Home/Logic/Types";

// GraphCms
const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl4zjegzn08ls01umbq7m9fxt/master"
);

const QUERY = gql`
  query Items($featured: Boolean!) {
    collectionBanners {
      id
      collectionName
      slug
      collectionCoverPhoto {
        url
      }
    }
    categories {
      id
      categoryName
      categoryCoverPhoto {
        url
      }
    }
    items(where: { featured: $featured }) {
      id
      productName
      productPrice
      slug
      productPhoto {
        url
      }
    }
    limitedItems {
      id
      productName
      productPrice
      productQuantity
      coverPhotoTitle
      rating
      description {
        text
      }
      coverPhoto {
        url
      }
      productPhoto {
        url
      }
    }
  }
`;

export const getStaticProps = async () => {
  const featured = true;
  const { collectionBanners, categories, items, limitedItems } =
    await graphcms.request(QUERY, { featured });
  return {
    props: { collectionBanners, categories, items, limitedItems },
    revalidate: 10,
  };
};

interface Props {
  collectionBanners: CollectionBannersType[];
  categories: CategoriesType[];
  items: ItemsType[];
  limitedItems: LimitedItemType[];
}

const Home: NextPage<Props> = ({
  collectionBanners,
  categories,
  items,
  limitedItems,
}: any) => {
  return (
    <div>
      <Head>
        <title>Workoutly Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/Logo.ico" />
      </Head>

      <main>
        <Nav />
        <Hero CollectionBanners={collectionBanners} />
        <Categories Categories={categories} />
        <FeaturedItems FeaturedItems={items} />
        <LimitedItem LimitedItems={limitedItems} />
        <Blog />
        <Footer CategoryList={categories} />
      </main>
    </div>
  );
};

export default Home;
