import type { NextPage } from "next";
import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import Nav from "../common/Nav";
import Hero from "../modules/Home/Hero";
import Categories from "../modules/Home/Categories";
import FeaturedItems from "../modules/Home/FeaturedItems";

// GraphCms
const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl4zjegzn08ls01umbq7m9fxt/master"
);

const QUERY = gql`
  query Items($featured: Boolean!) {
    collectionBanners {
      id
      collectionName
      collectionCoverPhoto {
        url
      }
    }
    categories {
      id
      categoryName
      categoryCoverPhoto {
        url
      }
    }
    items(where: { featured: $featured }) {
      productName
      productPrice
      productPhoto {
        url
      }
    }
  }
`;

export const getStaticProps = async () => {
  const featured = true;
  const { collectionBanners, categories, items } = await graphcms.request(
    QUERY,
    { featured }
  );
  return {
    props: { collectionBanners, categories, items },
    revalidate: 10,
  };
};

const Home: NextPage = ({ collectionBanners, categories, items }: any) => {
  return (
    <div>
      <Head>
        <title>Workoutly Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.ico" />
      </Head>

      <main>
        <Nav />
        <Hero CollectionBanners={collectionBanners} />
        <Categories Categories={categories} />
        <FeaturedItems FeaturedItems={items} />
      </main>
    </div>
  );
};

export default Home;
