import Head from "next/head";
import React from "react";
import Content from "../modules/UserPanel/Content";
import Sidebar from "../modules/UserPanel/Sidebar";

function UserPanel() {
  return (
    <div>
      <Head>
        <title>Workoutly Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/Logo.ico" type="image/x-icon" />
      </Head>
      <main style={{ display: "flex" }}>
        <Sidebar />
        <Content />
      </main>
    </div>
  );
}

export default UserPanel;
